displayName=Orb Hider Mini
author=OsrsNevermore
support=https://github.com/OsrsNevermore/Runelite-orb-hider-mini
description=Hides minimized minimap orbs
tags=orbs,orb,minimap,spec,hide
plugins=com.orbhidermini.OrbHiderminiPlugin